### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by w1r0x** [Difrex/surok#4]
May be we should use travis ci for tests?

**Comment by Difrex** [comment]
May be. Are you have some experience with this CI?

Build script(build/build.sh) is work. We need some unit/functional tests. 
I'm try to use Minimesos and it is work fine. 

Travis CI -> Build package -> Build surok base docker image -> Run minimesosFile -> tests

**Comment by Difrex** [comment]
I'm adding Travis CI and build is passed. 

Tests needed.
